### ISSUE TITLE
Create installation documentation

### ISSUE THREAD

**Issue by scytherswings** [scytherswings/Plex-Board#1]
Potential users will probably need to know how to install Plex-Board

**Comment by duramato** [comment]
Also an auto update feature will make it easier to update after the initial install
Git is a good candidate for it

**Comment by scytherswings** [comment]
Haha, yeah, you're right. I'll need to make sure all my automated testing passes before doing that, and that also would make it risky if I decided to redo the database structure in the future. That being said, being user friendly is what this project is about, so I think that's a reasonable goal to add.

**Comment by scytherswings** [comment]
I think I'm going to hold off on this until the project is a bit more feature filled. I don't want the overhead of document maintenance this early in the project. I can be reached on the gitter chat if anyone has questions.

**Comment by scytherswings** [comment]
I ended up writing some install instructions for testing tonight. Not finished but I think they should work.
