### ISSUE TITLE
add version to PB and dependancies to "about" section of UI

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#100]
would be good to AT LEAST have what version of PB they are running in the ABOUT portion.  Or, could add a watermark to the footer.  

Would also be good to add any and all dependency versions to the about page as well.

**Comment by scytherswings** [comment]
Do you mean system dependencies? Or gems? Both? All dependencies? lol

**Comment by seanvree** [comment]
all da dependancies!!! No, just the main programs that are required to run PB - so, Ruby, etc.

**Comment by scytherswings** [comment]
There's a lot of dependencies lol. Also you won't be able to see it if the application isn't running. I can display the version easily, that is a good idea for sure. What use case do you see for listing the dependencies?

**Comment by seanvree** [comment]
Na, Just the version of the main application is fine buddy.
