### ISSUE TITLE
Feature Request: Emby Support

### ISSUE THREAD

**Issue by Magic815** [scytherswings/Plex-Board#106]
So over a year ago, I stumbled upon the Network-Status-Page options (of which one fork was yours), and loved the idea of having that be a good monitor/landing page. Ever since, I've tried to find a way to make one of the forks work with Emby, but was never successful.

This was a thread I had made on the Emby forums almost a year ago, but no traction ever came from it:
https://emby.media/community/index.php?/topic/37329-network-status-page/

I would **love** to see Emby support with this new dashboard of yours, if possible! It would instantly become my landing page inside Organizr, and be the last piece I've been looking for on my server.

The thread link above shows a picture with some of the info that would be awesome to see. But here are some other ideas as well:
- Indication of what's currently being watched (maybe username info?)
- What has been recently added (maybe separate categories for Movies, TV, and Music)
- Maybe some basic stats/graphs (taking a page from PlexPy)? Things like number of movies, shows, episodes.

**Comment by scytherswings** [comment]
Hi @Magic815! Thanks for all the information! 

I consider every feature request I get and you can see my current "high-priority" board which is tracking the work necessary to get this project to 1.0 here: https://github.com/scytherswings/Plex-Board/projects/2 

Once we're 1.0, expanding support for other services will be much more doable.

**Comment by seanvree** [comment]
@Magic815  - 

As far as Organizr, I love that app, and it works like a charm.  I use it as my default tab.  

Screenshot:
http://imgur.com/nyTk2up

As far as Embi - that's up to @scytherswings .  I'm a PLEX guy myself.

**Comment by scytherswings** [comment]
This issue was moved to Porthole-Project/Porthole#1
