### ISSUE TITLE
Sonarr Support

### ISSUE THREAD

**Issue by camjac251** [scytherswings/Plex-Board#12]
Will PlexBoard Support things like Sonarr? I find this to be the best option vs sickrage and sickbeard.
Sonarr has a nice API that you can ask about in their irc channel

**Comment by scytherswings** [comment]
You know what, I hadn't actually spent much time searching for alternatives to Sickrage, I've been having some issues lately myself. I don't see a problem with adding support for Sonarr if it has an API to use. I'll have to go over my milestones again in order to re-prioritize things

**Comment by Foebik** [comment]
https://github.com/Sonarr/Sonarr/wiki/API

**Comment by scytherswings** [comment]
I'm going to hold off on integrations with other apps until things are more stable here.
