### ISSUE TITLE
Is this still under development?

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#55]
Also, I know there are several version of this project out there, but I can't seem to find one that works with IIS running on Windows?

 I THINK I got it installed correctly, but i'm getting the following error when running runserver.sh

C:\inetpub\wwwroot\Plex-Board>sh runserver.sh
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 2.13.4 (ruby 2.3.3-p222), codename: A Midsummer Code's Dream
* Min threads: 0, max threads: 16
* Environment: production
! Unable to load application: NameError: uninitialized constant Service::Resolv
C:/inetpub/wwwroot/Plex-Board/app/models/service.rb:14:in `<class:Service>': uninitialized constant Service::Resolv (NameError)
        from C:/inetpub/wwwroot/Plex-Board/app/models/service.rb:1:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:471:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:471:in `block in eager_load!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:469:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/engine.rb:469:in `eager_load!'
        from C:in `eager_load!'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from C:/Ruby23/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
        from C:/inetpub/wwwroot/Plex-Board/config/environment.rb:5:in `<top (required)>'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from config.ru:3:in `block in <main>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:184:in `instance_eval'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:184:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:170:in `eval'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:170:in `new_from_string'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/rack/builder.rb:161:in `parse_file'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/configuration.rb:129:in `load_rackup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/configuration.rb:96:in `app'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/runner.rb:113:in `load_and_bind'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/single.rb:79:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/lib/puma/cli.rb:215:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/puma-2.13.4/bin/puma:10:in `<top (required)>'
        from C:/Ruby23/bin/puma:22:in `load'
        from C:/Ruby23/bin/puma:22:in `<main>'

C:\inetpub\wwwroot\Plex-Board>

**Comment by scytherswings** [comment]
Sorry for not responding sooner. 

As far as running it on windows, I have never tried. I've developed it on Ubuntu 14.04 and worked on it in 16.04. Also if you're in the windows world, you should know that the mechanism that this project uses to live update will not work with Internet Explorer or Microsoft Edge as they do not support SSE. 

I'm not really sure why you're seeing that error, it looks like it doesn't know about the ruby `Resolv` library so I've added a require statement to that model. Let me know if it works.

**Comment by seanvree** [comment]
@scytherswings  - I got it running. (somewhate) the problem with RESOLV was that I had to drop the resolv.rb in the app/models dir. 

However, 

this is all I'm seeing now:

http://imgur.com/a/8OgBe

Anyway.  I'd love to see this project back up!

**Comment by scytherswings** [comment]
Ahhh it looks like your assets aren't coming through. Are you running the app in production? If so you'll need to run:
```
RAILS_ENV=production rake assets:clobber assets:precompile
```

Also, if you're working on it now I'll be reachable on gitter

**Comment by seanvree** [comment]
@scytherswings - I'll hop on Gitter
