### ISSUE TITLE
When added service is down, PB will fail

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#58]
Windows

If the service is added to PB when service is ONLINE and then service dies after...PB will fail. Also, if you stop the service then restart PB, it will still show the service as ONLINE. 

"We're sorry, but something went wrong.

If you are the application owner check the logs for more information."

ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.000 seconds)):
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:189:in `block in wait_poll'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `loop'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:180:in `wait_poll'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:135:in `block in poll'
  C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `synchronize'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:133:in `poll'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:425:in `acquire_connection'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  C:/Ruby23/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.5) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.5) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.5) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.2.5) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:31:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  puma (3.8.2) lib/puma/configuration.rb:224:in `call'
  puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
  puma (3.8.2) lib/puma/server.rb:435:in `process_client'
  puma (3.8.2) lib/puma/server.rb:299:in `block in run'
  puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by scytherswings** [comment]
I have increased the pool size, let me know if this fixes this behavior.

**Comment by seanvree** [comment]
@scytherswings - so the app doesn't crash anymore, but if the service is stopped, it's still reporting is up?  Doesn't look like anything is in the logs? I've tried with a couple different services - sabnzbd and sonarr

I, [2017-03-26T00:53:01.439518 #26704]  INFO -- :   Rendered services/_service.html.erb (0.5ms)
D, [2017-03-26T00:53:02.213226 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT COUNT(*) FROM "plex_services"
D, [2017-03-26T00:53:02.213226 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT COUNT(*) FROM "services"[0m
D, [2017-03-26T00:53:02.214207 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT "plex_services".* FROM "plex_services"
D, [2017-03-26T00:53:02.214207 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT "services".* FROM "services"[0m
D, [2017-03-26T00:53:03.440028 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT COUNT(*) FROM "plex_services"
D, [2017-03-26T00:53:03.440529 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT COUNT(*) FROM "services"[0m
D, [2017-03-26T00:53:03.440529 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT "plex_services".* FROM "plex_services"
D, [2017-03-26T00:53:03.440529 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT "services".* FROM "services"[0m
D, [2017-03-26T00:53:04.214864 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT COUNT(*) FROM "plex_services"
D, [2017-03-26T00:53:04.214864 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT COUNT(*) FROM "services"[0m
D, [2017-03-26T00:53:04.214864 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT "plex_services".* FROM "plex_services"
D, [2017-03-26T00:53:04.214864 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT "services".* FROM "services"[0m
D, [2017-03-26T00:53:06.343268 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT "plex_services".* FROM "plex_services"
D, [2017-03-26T00:53:06.343268 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT "services".* FROM "services"[0m
D, [2017-03-26T00:53:06.456489 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT COUNT(*) FROM "plex_services"
D, [2017-03-26T00:53:06.456489 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT COUNT(*) FROM "services"[0m
D, [2017-03-26T00:53:06.456489 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT "plex_services".* FROM "plex_services"
D, [2017-03-26T00:53:06.456489 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT "services".* FROM "services"[0m
D, [2017-03-26T00:53:07.225491 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT COUNT(*) FROM "plex_services"
D, [2017-03-26T00:53:07.226473 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT COUNT(*) FROM "services"[0m
D, [2017-03-26T00:53:07.226473 #26704] DEBUG -- :   [1m[35mCACHE (0.0ms)[0m  SELECT "plex_services".* FROM "plex_services"
D, [2017-03-26T00:53:07.226473 #26704] DEBUG -- :   [1m[36mCACHE (0.0ms)[0m  [1mSELECT "services".* FROM "services"[0m

**Comment by scytherswings** [comment]
Ahhhh.... Yeah.. I know what I did. I broke the logic for checking online state thinking to make it more reliable.

**Comment by seanvree** [comment]
Is this working for you Andrew, or is it just a windows thing?

**Comment by scytherswings** [comment]
I changed the logic back in the `hotifx` branch so that rejected connections mark the service as down and I have a test that reflects the behavior as working. This should work correctly regardless of the OS. I'll play around with it tonight again to see what it does under different conditions.

**Comment by scytherswings** [comment]
Yep the hotfix branch works as I expect, services go offline when i disconnect them from the server and when the server rejects their connections. Merging to master.

**Comment by seanvree** [comment]
@scytherswings  - Got it.  What do you need my help with brotha?

**Comment by scytherswings** [comment]
@seanvree what feature do you want to see next? I'm looking into an old gem that can help me display rails logs live but it's going to take some fiddling. Is log tunneling what you want next? Do you have any suggested ways to implement it? If you're good with HTML/Javascript I'd totally be up for collaborating on it.

**Comment by seanvree** [comment]
@scytherswings  - personally, I'd love to see the logs deal - now are you just talking rails logs?  Because I was talking like the service logs - like Plex, Sabnzbd, deluge.  I'll work on it tonight.

**Comment by scytherswings** [comment]
@seanvree Yeah I was initially going to get the rails logs fed in so that you wouldn't have to dig for any files. I didn't have any immediate ideas on how to pipe logs from those other services. If you can figure out the HTML/javascript for iFraming those logs and figuring out what you need from me to build those iframes (like urls etc.) I can supply them into the HTML. If you want to chat on gitter we can, might be faster

**Comment by seanvree** [comment]
@scytherswings  - I know how to pipe in the files.  Let's chat tomo.  I'll do some research and test tonight.

**Comment by scytherswings** [comment]
Ok awesome, works for me. I'll keep experimenting with feeding these rails logs in for tonight. Gonna have to turn in soon though.

**Comment by seanvree** [comment]
Yeah, good deal.  I'll have something for tomo.

**Comment by seanvree** [comment]
Yo buddy,   Had some awesome Easy ideas to implement. You gonna be on Gitter later?



_____________________________________
Sean J. Vreeland
CPT, U.S. Army (Ret.)
MBA Candidate - Seattle University

m: (801) 471-6023
