### ISSUE TITLE
Suggestion:  Seperate "recently added" and "now playing"?

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#59]
I personally would like to see two different tables, now playing at the top and recently added below that?

just my presence.  What do you think?

**Comment by scytherswings** [comment]
Two separate carousels? Or what's your thought? Rough MS paint drawing might go a long way lol

**Comment by seanvree** [comment]
@scytherswings  - well, wouldn't need a carousels for the Now playing....I guess that would just be static.  

Yeah, let me do some painting. LOL
