### ISSUE TITLE
Plex Recently Added using wrong logic to differentiate items

### ISSUE THREAD

**Issue by scytherswings** [scytherswings/Plex-Board#69]
The UUID from plex is for the section, not the PRA item. The logic needs to be changed to use some sort of dynamic key built from the title of the media.

**Comment by scytherswings** [comment]
It still works, it just doesn't update as often as you might expect.

**Comment by seanvree** [comment]
This isn't working at all on windows FYI.

**Comment by scytherswings** [comment]
@seanvree yeah it won't work like you would expect on any system, I'll see what I can do about it tonight.

**Comment by scytherswings** [comment]
Fixed in latest push
