### ISSUE TITLE
compiling execJS [windows] (investigation needed)

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#70]
OS: Windows10E x64
git version 2.12.2.windows.1
Chocolatey v0.10.5
Bundler version 1.14.6
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
puma version 3.8.2
gem -v 2.5.2

---------------------

On windows from elevated CMD prompt:

C:\plex-board
SH serversetup.SH

--------------------
Compiling assets
rake aborted!
ExecJS::ProgramError: TypeError: Object doesn't support this property or method

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

Creating images directory

Finished. Run ./runServer.sh to start the server! It runs on port 3000 by default.

C:\Plex-Board>

-------------------

The server WILL run after that, but I'm not sure what that error means?

**Comment by scytherswings** [comment]
I think this has to do with windows and your javascript runtimes, can you install `nodejs` any see if it happens again? http://stackoverflow.com/questions/12520456/execjsruntimeerror-on-windows-trying-to-follow-rubytutorial

**Comment by scytherswings** [comment]
Dependencies were out of date.
