### ISSUE TITLE
Feature Request:  Change Name of header

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#74]
Need a way to change the "name" of the server - So maybe the top middle header we could add a Feild that would appear in plain text:  IE:  "sean's PLEX server" or something like that.

**Comment by scytherswings** [comment]
Do you mean you want to replace "Plex-Board" in the navbar with some other text?

**Comment by seanvree** [comment]
Not necessarily.  It's just too blank in the top middle LOL

**Comment by scytherswings** [comment]
This issue was moved to Porthole-Project/Porthole#19
