### ISSUE TITLE
POSSIBLE BUG:  Windows dependency crashing IIS / OS [CRITICAL]

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#75]
currently investigating.

Issue: Issue: 
IIS fails to launch after installing a dependency. 

Possible cause:

One of the windows dependencies MAY be causing the default app pool in IIS to crash and NOT start. 
Related to a x86 script and/or application calling ASP x64 processes causing the DefaultAPPpool to crash and possible memory leak in Windows OS environment. 

TEMP SOLUTION:

Disable all non-native windows services
Reinstall all version of ASP.net
relaunch default app pool
relaunch IIS.

**Comment by scytherswings** [comment]
I'm not sure this is the fault of Plex-Board, there's too many variables to say for sure.

**Comment by seanvree** [comment]
True.   I just wanted to open this until we figured out what it was. 

Issue was windows ASP.net 4.0 crashing defaultapppool.  

WINDOWS INTERNAL issue.

**Comment by scytherswings** [comment]
Ok we can update this with what we find out.

**Comment by seanvree** [comment]
I would say just delete this if you can.

**Comment by scytherswings** [comment]
Oooook
