### ISSUE TITLE
Feature Request:  BASIC server loads?

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#90]
I think we should add BASIC server loads from https://github.com/scytherswings/Network-Status-Page

CPU Load, RAM Load, LAN/WAN speed. 

VERY basic.

**Comment by scytherswings** [comment]
This is kindof a duplicate of #10 but your wording is less specific than that so I'll keep this ticket around.

**Comment by seanvree** [comment]
Yeah, I'll delete this one.
