### ISSUE TITLE
Feat Req:  Service Indicator Colors

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#93]
I think it would be cool to add the colors based on the following:

Green:  Currently UP
Yellow:  Currently UP, but had failures in the past X hours
Red:  Currently DOWN.  

Possible?

**Comment by scytherswings** [comment]
Totally possible. I think Network Status Page originally used only green and yellow because it's easy on the eyes. Also green and yellow are color-blind friendly I think. But yeah we can enhance the status indicators for sure

**Comment by scytherswings** [comment]
This issue was moved to Porthole-Project/Porthole#8
