### ISSUE TITLE
Add Server Time

### ISSUE THREAD

**Issue by seanvree** [scytherswings/Plex-Board#95]
I think a server time node (In the top left or right) would be good.  Something that would continuously update against a user-chosen time server.  That way you can tell if the page has stalled?

**Comment by scytherswings** [comment]
@seanvree I could simply put a little status indicator somewhere on the page. Like a blue/red circle to tell you live/offline etc.

**Comment by seanvree** [comment]
@scytherswings - YES.  Needed, sometimes I can't tell if the browser needs to be refreshed.  Also, I think the clock isn't a bad idea?!  Not sure.  But some time of indicator.

**Comment by scytherswings** [comment]
This issue was moved to Porthole-Project/Porthole#7
